---
# tasks file for db_server
- name: update repo index for db server
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"


- name: install mariadb
  apt: 
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: starting mariadb
  service:
    name: mariadb
    state: restarted
    enabled: true