---
# tasks file for file_server
- name: update repo index for file_server
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install samba
  apt:
    name: samba
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: starting samba
  service:
    name: smbd
    state: restarted
    enabled: true